### ISSUE TITLE
Nxdomain

### ISSUE THREAD

**Issue by UnderFenex** [lukaszsamson/telemetry_metrics_zabbix#1]
I'm trying to send information using the example, and I get this message:

> could not send messages due to :nxdomain

**Comment by lukaszsamson** [comment]
Does your machine have network connection to your zabbix trapper? Please verify that your host and port settings are valid. This error means that your machin is not able to resolve the host address.

**Comment by UnderFenex** [comment]
Hi, I got confused. Does this is the workflow? Is it 1 or 2?

1. Telemetry -> TelemetryMetricsZabbix -> Zabbix Server
2. Telemetry -> TelemetryMetricsZabbix -> Zabbix Agent (Local) -> Zabbix Server

**Comment by UnderFenex** [comment]
Now I am getting this warning:

[warn] Elixir.TelemetryMetricsZabbix: server could not process 1 out of 1 messages. Message keys was: ["http.request.latency[\"me\"]"]

This is the execute function:
    :telemetry.execute([:http, :request], %{latency: System.monotonic_time() - start}, %{endpoint: "me", method: "GET"})

This is the telemetry one:
      Telemetry.Metrics.sum("http.request.latency", unit: {:native, :millisecond}, tags: [:endpoint])

It seems, that it's no fetching latency, should I use Statix?/ Also I don't see any logs on my zabbix server

**Comment by lukaszsamson** [comment]
The data flow is
Telemetry -> TelemetryMetricsZabbix -> Zabbix Server

> [warn] Elixir.TelemetryMetricsZabbix: server could not process 1 out of 1 messages. Message keys was: ["http.request.latency["me"]"]

This means that you communication is now working but your zabbix server is rejecting your measurement.
You need to create a zabbix trapper that consumes measurements with key: `http.request.latency["me"]`.
Unfortunately zabbix needs a trapper for every key you are going to send. It's best to use zabbix LLD macros for that.

**Comment by UnderFenex** [comment]
Hi I configured the trapper as this:

![image](https://user-images.githubusercontent.com/3832413/98993695-ccb98180-24fc-11eb-8cfd-e3a174a9bd9f.png)

However it keeps showing the same error. Is there a way to show in Elixir log what is the data present in http.request?

**Comment by UnderFenex** [comment]
Using the log, I'm able to see the parameters
summary("http.request.latency", unit: {:native, :millisecond}, tags: [:endpoint])

[info] Received [:http, :request] event. Request duration: 206, Route: me

However, I think the issue is with the zabbix trapper, can you help me?

**Comment by lukaszsamson** [comment]
The trapper key looks good. For simplicity I use the same name as key. Is the trapper item on the correct zabbix host? IIRC you have to set the same `hostname` in telemetry_metrics_zabbix config. Try changing Type of information to numeric (I didn't try it with text). I also don't have anything selected in Applications.
Note also that in my experience there is about 2 minute delay before zabbix picks up the new config after an update.

**Comment by lukaszsamson** [comment]
> Is there a way to show in Elixir log what is the data present in http.request?

Zabbix doesn't use http requests but a custom binary TCP based zabbix sender protocol https://zabbix.org/wiki/Docs/protocols/zabbix_sender/4.0

If you need to debug protocol messages it's best to fork this or my other library https://github.com/lukaszsamson/elixir_zabbix_sender (telemetry_metrics_zabbix uses it to comunicate with zabbix server)

**Comment by UnderFenex** [comment]
Got it working :smile: 

The issue was that I was issue PSK encryption (as I usually use for Zabbix Agents). Is there a way to configure the psk value in the  configuration?

```
config :telemetry_metrics_zabbix, :config,
  host: "myzabbixserver.com",
  port: 10051,
  hostname: "MyServer",
  batch_window_size: 1000,
  timestamping: true
```

**Comment by lukaszsamson** [comment]
> Got it working 😄

I'm glad to hear that

> Is there a way to configure the psk value in the configuration?

It's not supported ATM. Please send a PR
